// Package shim installs and resolves PATH shims — devhost's activation layer
// on macOS. A shim sits in front of a runtime launcher (node, ...) on PATH
// and delegates to `devhost shim-exec`, which applies the project environment
// at the FINAL exec. That late injection is the whole point: macOS SIP strips
// DYLD_* style variables across /bin/sh and /usr/bin/env hops, but a shim
// re-applies plain env vars right before the real binary starts, so no
// upstream stripping can break it. Outside a .devhost tree, shims add nothing
// but a PATH lookup.
package shim

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"slices"
	"strings"

	"github.com/wickedev/devhost/internal/inject"
)

// DefaultTools are the runtime launchers `devhost setup` offers to shim.
// Anything with a `#!/usr/bin/env node` shebang (npm, npx, next, vite...)
// routes through the node shim automatically; same for the other runtimes'
// script ecosystems. cargo and go are launchers of *native* servers: the
// locally-built binaries they run are not Apple platform binaries, so the
// bind() interposer injected at the shim's exec survives into them — this is
// what isolates a `cargo run` / `go run` dev server even when the chain
// started at a SIP-protected hop like `/usr/bin/make`. Install skips tools
// not present on the machine so a shim never shadows a launcher that doesn't
// actually exist (scripts probe with `command -v`, and a lying PATH entry
// would break them).
var DefaultTools = []string{"node", "python", "python3", "ruby", "cargo", "go"}

const scriptTemplate = `#!/bin/sh
# devhost shim for %[1]s — generated by 'devhost setup'. Do not edit.
# Delegates to 'devhost shim-exec', which injects the per-project loopback IP
# and execs the real %[1]s. Falls back to the real binary if devhost is gone.
if command -v devhost >/dev/null 2>&1; then
  exec devhost shim-exec %[1]s -- "$@"
fi
SHIM_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
PATH=$(printf %%s "$PATH" | awk -v RS=: -v d="$SHIM_DIR" '$0 != d' | paste -sd: -)
export PATH
exec %[1]s "$@"
`

// Dir returns the shim directory.
func Dir() string { return filepath.Join(inject.ConfigDir(), "shims") }

// customFile records tools the user shimmed beyond DefaultTools
// (`devhost shim add`), one name per line, so setup/upgrade re-installs them.
func customFile() string { return filepath.Join(inject.ConfigDir(), "shim-tools") }

// CustomTools returns the user-added shim tools, in file order.
func CustomTools() []string {
	data, err := os.ReadFile(customFile())
	if err != nil {
		return nil
	}
	var tools []string
	for _, line := range strings.Split(string(data), "\n") {
		if t := strings.TrimSpace(line); t != "" && !slices.Contains(tools, t) {
			tools = append(tools, t)
		}
	}
	return tools
}

// AllTools is the full shim set: defaults plus user-added tools.
func AllTools() []string {
	tools := slices.Clone(DefaultTools)
	for _, t := range CustomTools() {
		if !slices.Contains(tools, t) {
			tools = append(tools, t)
		}
	}
	return tools
}

// AddCustom persists tool in the custom shim set. Returns false if it was
// already there (or is a default).
func AddCustom(tool string) (bool, error) {
	if slices.Contains(AllTools(), tool) {
		return false, nil
	}
	if err := os.MkdirAll(inject.ConfigDir(), 0o755); err != nil {
		return false, err
	}
	tools := append(CustomTools(), tool)
	return true, os.WriteFile(customFile(), []byte(strings.Join(tools, "\n")+"\n"), 0o644)
}

// RemoveCustom drops tool from the custom set and deletes its shim. Returns
// false if it wasn't a custom tool.
func RemoveCustom(tool string) (bool, error) {
	tools := CustomTools()
	if !slices.Contains(tools, tool) {
		return false, nil
	}
	tools = slices.DeleteFunc(tools, func(t string) bool { return t == tool })
	content := ""
	if len(tools) > 0 {
		content = strings.Join(tools, "\n") + "\n"
	}
	if err := os.WriteFile(customFile(), []byte(content), 0o644); err != nil {
		return false, err
	}
	if err := os.Remove(filepath.Join(Dir(), tool)); err != nil && !os.IsNotExist(err) {
		return true, err
	}
	return true, nil
}

// Install writes shims for the given tools that exist on this machine and
// returns the shim directory plus the tools actually shimmed.
func Install(tools []string) (string, []string, error) {
	dir := Dir()
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return "", nil, err
	}
	if _, err := inject.EnsureInjector(); err != nil {
		return "", nil, err
	}
	var installed []string
	for _, tool := range tools {
		if _, err := RealBinary(tool); err != nil {
			continue // tool not on this machine — don't shadow it with a shim
		}
		p := filepath.Join(dir, tool)
		if err := os.WriteFile(p, fmt.Appendf(nil, scriptTemplate, tool), 0o755); err != nil {
			return "", nil, err
		}
		installed = append(installed, tool)
	}
	return dir, installed, nil
}

// RealBinary resolves tool on PATH, skipping the shim directory, so
// shim-exec can hand off to the genuine launcher (which may itself be a
// version manager shim — asdf, mise — whose semantics are preserved).
func RealBinary(tool string) (string, error) {
	shimDir := Dir()
	for _, d := range filepath.SplitList(os.Getenv("PATH")) {
		if d == "" || d == shimDir {
			continue
		}
		p := filepath.Join(d, tool)
		if info, err := os.Stat(p); err == nil && !info.IsDir() && info.Mode()&0o111 != 0 {
			return p, nil
		}
	}
	return "", fmt.Errorf("real %q not found on PATH outside the shim dir", tool)
}

// ResolveThroughManagers follows a version-manager shim script (asdf, mise)
// to the actual runtime binary. Needed on macOS only: those shims are shell
// scripts, and SIP strips DYLD_INSERT_LIBRARIES when /bin/bash execs, which
// would silently drop the bind() interposer. Executing the real Mach-O
// binary directly keeps the injection alive. Must run with the project as
// cwd — the managers resolve versions from .tool-versions there.
func ResolveThroughManagers(path, tool string) string {
	f, err := os.Open(path)
	if err != nil {
		return path
	}
	head := make([]byte, 2)
	n, _ := f.Read(head)
	f.Close()
	if n < 2 || head[0] != '#' || head[1] != '!' {
		return path // a real binary — nothing to bypass
	}
	for _, mgr := range []string{"asdf", "mise"} {
		bin, err := exec.LookPath(mgr)
		if err != nil {
			continue
		}
		out, err := exec.Command(bin, "which", tool).Output()
		if err != nil {
			continue
		}
		real := strings.TrimSpace(string(out))
		if info, err := os.Stat(real); err == nil && !info.IsDir() && info.Mode()&0o111 != 0 {
			return real
		}
	}
	return path
}
