// Package shim installs and resolves PATH shims — devhost's activation layer
// on macOS. A shim sits in front of a runtime launcher (node, ...) on PATH
// and delegates to `devhost shim-exec`, which applies the project environment
// at the FINAL exec. That late injection is the whole point: macOS SIP strips
// DYLD_* style variables across /bin/sh and /usr/bin/env hops, but a shim
// re-applies plain env vars right before the real binary starts, so no
// upstream stripping can break it. Outside a .devhost tree, shims add nothing
// but a PATH lookup.
package shim

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/wickedev/devhost/internal/inject"
)

// DefaultTools are the runtime launchers shimmed by `devhost setup`.
// Anything with a `#!/usr/bin/env node` shebang (npm, npx, next, vite...)
// routes through the node shim automatically.
var DefaultTools = []string{"node"}

const scriptTemplate = `#!/bin/sh
# devhost shim for %[1]s — generated by 'devhost setup'. Do not edit.
# Delegates to 'devhost shim-exec', which injects the per-project loopback IP
# and execs the real %[1]s. Falls back to the real binary if devhost is gone.
if command -v devhost >/dev/null 2>&1; then
  exec devhost shim-exec %[1]s -- "$@"
fi
SHIM_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
PATH=$(printf %%s "$PATH" | awk -v RS=: -v d="$SHIM_DIR" '$0 != d' | paste -sd: -)
export PATH
exec %[1]s "$@"
`

// Dir returns the shim directory.
func Dir() string { return filepath.Join(inject.ConfigDir(), "shims") }

// Install writes shims for the given tools and returns the shim directory.
func Install(tools []string) (string, error) {
	dir := Dir()
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return "", err
	}
	if _, err := inject.EnsureInjector(); err != nil {
		return "", err
	}
	for _, tool := range tools {
		p := filepath.Join(dir, tool)
		if err := os.WriteFile(p, fmt.Appendf(nil, scriptTemplate, tool), 0o755); err != nil {
			return "", err
		}
	}
	return dir, nil
}

// RealBinary resolves tool on PATH, skipping the shim directory, so
// shim-exec can hand off to the genuine launcher (which may itself be a
// version manager shim — asdf, mise — whose semantics are preserved).
func RealBinary(tool string) (string, error) {
	shimDir := Dir()
	for _, d := range filepath.SplitList(os.Getenv("PATH")) {
		if d == "" || d == shimDir {
			continue
		}
		p := filepath.Join(d, tool)
		if info, err := os.Stat(p); err == nil && !info.IsDir() && info.Mode()&0o111 != 0 {
			return p, nil
		}
	}
	return "", fmt.Errorf("real %q not found on PATH outside the shim dir", tool)
}
